### ISSUE TITLE
Please indicate the version of PyTorch and torchvision needed

### ISSUE THREAD

**Issue by mhucka** [seuretm/printed-vs-handwritten#3]
Thanks for making this software available. I've been trying to make it work, but cannot due to not knowing which version of the dependencies are needed. (Pytorch 1.5.0 does not seem to work; you get the error `AttributeError: 'AvgPool2d' object has no attribute 'divisor_override'` when you try to run the demo.)

Can you please indicate which versions of PyTorch and torchvision are needed?

**Comment by Leungfranklin** [comment]
I encounter the same problem

**Comment by shridharyadav88** [comment]
I am facing the same problem anyone able to solve this?

**Comment by LuluBeatson** [comment]
Same here!
I also tried a python 3.5 environment with 2 older 2019 versions of pytorch:
1. `conda install pytorch==1.0.1 torchvision==0.2.2 -c pytorch`
  This gave me `AttributeError: 'ReLU' object has no attribute 'threshold'`
2. `conda install pytorch==1.0.0 torchvision==0.2.1 -c pytorch`
  This gave me:
    ```
    Traceback (most recent call last):
      File "classify.py", line 4, in <module>
        from ocrd_typegroups_classifier.network.densenet import densenet121
      File "/Users/lulubeatson/Documents/GitHub/printed-vs-handwritten/ocrd_typegroups_classifier/network/densenet.py", line 2, in <module>
        import torch
      File "/Users/lulubeatson/opt/anaconda3/envs/py35/lib/python3.5/site-packages/torch/__init__.py", line 84, in <module>
        from torch._C import *
    ImportError: dlopen(/Users/lulubeatson/opt/anaconda3/envs/py35/lib/python3.5/site-packages/torch/_C.cpython-35m-darwin.so, 0x0009): Symbol not found: _cblas_sgemm_alloc
      Referenced from: /Users/lulubeatson/opt/anaconda3/envs/py35/lib/python3.5/site-packages/torch/lib/libmkldnn.0.dylib
      Expected in: /Users/lulubeatson/opt/anaconda3/envs/py35/lib/libmkl_rt.dylib
    ```

**Comment by LuluBeatson** [comment]
@subhadeepkaran has a solution in another issue thread: https://github.com/seuretm/printed-vs-handwritten/issues/1#issuecomment-631097084
